### ISSUE TITLE
can't get the activation site to work

### ISSUE THREAD

**Issue by sprue31** [mludowise/AppleTV-XFinity-Activation#6]
When I log into this site: https://mludowise.github.io/AppleTV-XFinity-Activation/  I can't click on the network to put in the code.  The page looks like it isn't loading properly. I have a MacBook pro and tried it on safari and then I tried it on chrome.  Neither time did the page load properly so I can click the network to put in the activation code.  Help!

**Comment by mludowise** [comment]
I see the problem - it looks like the 3rd party CSS library I'm using isn't loading. I'll try to get a fix up within the next couple hours.

Thank you for reporting this issue.

**Comment by mludowise** [comment]
This should be fixed now. 

You may need to refresh your browser's cache to see the fix. You can do this by holding down the alt key while pressing the refresh button.
